### PR TITLE
Removing REST token

### PR DESCRIPTION
**Pull request by rafaelh**
This looks like a cool project, but please don't commit REST tokens to a public repository.

### CODE REVIEW

**Comment by jthoward64** [comment]
Ah thanks, goood catch. That token is not actually active though (was just a test key that was deleted after a couple minutes). Out of curiosity, how did you come across this repo?

**Comment by rafaelh** [comment]
I'm part of the StarRez security team. We monitor github and other places for any repository containing our company name. Every couple of months we find credentials committed. When we tested the token was valid, so you'll need to get the University to  reactivate your account.

**Comment by jthoward64** [comment]
> I'm part of the StarRez security team. We monitor github and other places for any repository containing our company name. Every couple of months we find credentials committed. When we tested the token was valid, so you'll need to get the University to reactivate your account.

Appreciate the tip

**Comment by jthoward64** [comment]
> I'm part of the StarRez security team. We monitor github and other places for any repository containing our company name. Every couple of months we find credentials committed. When we tested the token was valid, so you'll need to get the University to  reactivate your account.

Appreciate the tip, although I assure you that as of last week I had no active REST credentials on my account. I haven't used used any of the StarRez REST API or StarQL API in a few weeks as I don't have access to the docs for them.

**Comment by jthoward64** [comment]
I will note though that if all that's been done in other repos with exposed credentials that simply deleting the file is insufficient to remove it. You'd need to rewrite history to remove the file from when it was first added using something like an interactive rebase.

**Comment by rafaelh** [comment]
I appreciate the follow up. I'm aware that deleting the file won't remove the token from the history, hence disabling the account temporarily, so that the token can be rotated. The University of Kentucky manages their own service, so it's possible your token was cloned between two environments, and remained active in Dev. We respond as a precaution; in this case it sounds like it was a minor issue.

**Comment by jthoward64** [comment]
> I appreciate the follow up. I'm aware that deleting the file won't remove the token from the history, hence disabling the account temporarily, so that the token can be rotated. The University of Kentucky manages their own service, so it's possible your token was cloned between two environments, and remained active in Dev. We respond as a precaution; in this case it sounds like it was a minor issue.

Gotcha, nevertheless I appreciate the heads up

**Pull request merged**
